### ISSUE TITLE
Module not found: Can't resolve '#apg-lite'

### ISSUE THREAD

**Issue by kambie10** [jellydn/next-swagger-doc#1032]
### Describe the bug

I have problem with module '#apg-lite'

![Screenshot 2024-05-13 at 10 14 01](https://github.com/jellydn/next-swagger-doc/assets/38092016/64ef13e3-0d1a-4356-954c-23fea7a80bcb)

we need delete '#'

### Reproduction

we need delete '#'

### System Info

```Shell
-
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rodrigonzalz** [comment]
I am also facing this issue, why was this close?
