### ISSUE TITLE
Error: No API definition provided

### ISSUE THREAD

**Issue by mariohmol** [jellydn/next-swagger-doc#105]
Hi there!!

Thanks a lot for this repo!

I´m trying to use it in a simple repo for testing, but it just gives me ' No API definition provided' 

I could make the endpoint `/api/doc` to spit out the json but the `api-doc` just shows me the ` No API definition provided`

If I use directly like this, it works

```
import SwaggerUI from 'swagger-ui-react';
import 'swagger-ui-react/swagger-ui.css';

const ApiDoc = () => <SwaggerUI 
url="/api/doc" />
```

Thanks

**Comment by jellydn** [comment]
Hi @mariohmol Thank you for filing the issue. Do you have a notation on your code? e.g:

```
/**
 * @openapi
 * /:
 *   get:
 *     description: Welcome to swagger-jsdoc!
 *     responses:
 *       200:
 *         description: Returns a mysterious string.
 */
app.get('/', (req, res) => {
  res.send('Hello World!');
});

```

If not, please try to follow the convention by https://github.com/Surnet/swagger-jsdoc

**Comment by mariohmol** [comment]
Yes, the same we have in the Readme, so when I visited /api/doc I got the correct json response.

Seems that the fronend swagger was not getting the json from the correct url?

**Comment by jellydn** [comment]
Could you create a repository repository? Then I could take a look. I guess there is a typo (space/indention) on comment on your app. Thanks.

**Comment by mariohmol** [comment]
but the json has been generated.. and using the same json I could make it work with pure swagger-js

**Comment by jellydn** [comment]
Sorry, I can't produce the issue so I will close this one. Thanks.

**Comment by jellydn** [comment]
Here is my example if you want to take a try.

```
mkdir test
npx degit jellydn/next-swagger-doc/example
yarn && yarn build && yarn start
```
