### ISSUE TITLE
Outdated glob dependency

### ISSUE THREAD

**Issue by ZadynB** [jellydn/next-swagger-doc#1149]
### Describe the bug

Not really a bug, but the version on the glob module is outdated and throws a warning when installing

### Reproduction

do the npm install next-swagger-doc

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i5-1335U
    Memory: 3.93 GB / 15.20 GB
  Binaries:
    Node: 22.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 130.0.6723.60
    Edge: Chromium (129.0.2792.65)
    Internet Explorer: 11.0.19041.4355
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jellydn** [comment]
Hi @ZadynB Could you share the npm logs? I didn't notice this issue with yarn or pnpm. Thanks.

**Comment by ZadynB** [comment]
Hey @jellydn, here is a screenshot of the npm logs:

![image](https://github.com/user-attachments/assets/6b16fc29-52c8-4868-ac94-f158c97e6da6)

**Comment by ZadynB** [comment]
Hey @jellydn, here is a screenshot of the npm logs:
![image](https://github.com/user-attachments/assets/a287bd6c-96de-4ec0-ad5d-7bda9a4a8bf6)
