### ISSUE TITLE
[Feature suggestion] Expand options for definition

### ISSUE THREAD

**Issue by tpedersen123** [jellydn/next-swagger-doc#144]
Loving the package, thank you so much @jellydn and team.

It would be nice to add more fields from the basic structure
https://swagger.io/docs/specification/basic-structure/
Info and servers more specifically. 

I see https://github.com/Surnet/swagger-jsdoc has an option to define these in a JSON or Yaml file?

**Comment by jellydn** [comment]
Thanks. I will look into this one later.

**Comment by tpedersen123** [comment]
Ok, let me know if you need help :-)

**Comment by jellydn** [comment]
Hi all. I will publish new version for this issue soon.

**Comment by jellydn** [comment]
Closed by https://github.com/jellydn/next-swagger-doc/releases/tag/v0.2.0 Please let me know if any issue. Thanks.
