### ISSUE TITLE
Swagger component schemas features

### ISSUE THREAD

**Issue by pahrizal** [jellydn/next-swagger-doc#195]
How to implement component schemas in `withSwagger`? is it possible to add `schemaFolder` like the `apiFolder` options? Thank you

**Comment by jellydn** [comment]
Thanks @pahrizal for filing the issue and pull request #196 

I have just release [new version](https://github.com/jellydn/next-swagger-doc/releases/tag/v0.2.1) with [example app](https://github.com/jellydn/next-swagger-doc/commit/f423d4c7448fc92f2d3200735854fc94fa27f713). Please take a try and let me know if any issue.

**Comment by pahrizal** [comment]
> Thanks @pahrizal for filing the issue and pull request #196
> 
> I have just release [new version](https://github.com/jellydn/next-swagger-doc/releases/tag/v0.2.1) with [example app](https://github.com/jellydn/next-swagger-doc/commit/f423d4c7448fc92f2d3200735854fc94fa27f713). Please take a try and let me know if any issue.

 look's good to me. Really happy to contribute, and thanks for adding me  @jellydn ,
