### ISSUE TITLE
A way to import from a separate file

### ISSUE THREAD

**Issue by felipenmoura** [jellydn/next-swagger-doc#202]
When using this notation with decorators in comments, some APIs will have hundreds of lines of YAML only for the documentation, leaving the source code way down in the file.
Also, editing these comments (specially because of the ` * ` in each line) makes it either hard to edit (prone to human error) or require plugins and extensions in editors.

My suggestion goes like this:

```js
/*
 * @swagger import ./.swagger
 */
export async function () {
  ...
};
```

In this case, there is a file `.swagger` right next to the source code.

Another option, perhaps
```js
/*
 * @swagger
 * @import ../my/swagger/file.yaml
 */
export async function () {
  ...
};
```

**Comment by jellydn** [comment]
Hi @felipenmoura 
There is an option for you to scanning the folder. I think that works for your use case, right?

```ts
import { withSwagger } from 'next-swagger-doc';

const swaggerHandler = withSwagger({
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Next Swagger API Example',
      version: '0.1.0',
    },
  },
  schemaFolders: ['models'],
});
export default swaggerHandler();
```

Please take a look on the example app https://github.com/jellydn/next-swagger-doc/blob/main/example/README.md for more detail. Thanks

**Comment by felipenmoura** [comment]
awesome, I will check that out, thanks :)

**Comment by MGough** [comment]
I found this issue when trying to load some of my data OpenAPI schema from a `.yaml` file, similar to the example from @felipenmoura , but I couldn't get the `schemaFolders` option to do what I wanted, and due to how this library wraps `swagger-jsdoc` I couldn't alter the input.

In my case I have some YAML openAPI files which are used to generate Typescript types. I then reference those newly generate Types in my endpoint JSDoc. Trying to combine the two is where it became tricky. I've managed this by tweaking this library so that it can also reference YAML files:
```
export function createSwaggerSpec({
  apiFolder = 'pages/api',
  schemaFolders = [],
  ...swaggerOptions
}: SwaggerOptions = defaultOptions) {
  const scanFolders = [apiFolder, ...schemaFolders];

  const options: Options = {
    apis: scanFolders.flatMap(apiFolder => {
      const buildApiDirectory = join(process.cwd(), '.next/server', apiFolder);
      const apiDirectory = join(process.cwd(), apiFolder);
      return [
        `${apiDirectory}/**/*.js`,
        `${apiDirectory}/**/*.ts`,
        `${apiDirectory}/**/*.tsx`,
        `${buildApiDirectory}/**/*.js`,
        `${apiDirectory}/**/*.yaml`,
        `${buildApiDirectory}/**/*.yaml`,
      ];
    }), // files containing annotations as above
    ...swaggerOptions,
  };

  return swaggerJsdoc(options);
}
```

Is this something that you'd be willing to add to this library?

**Comment by jellydn** [comment]
Hi @MGough Thanks for bringing this up again. I've just released a new version for testing the new option.

```
- Support *.swagger.yaml
```

Please take a try and let me know if that works for you. Cheer.

https://github.com/jellydn/next-swagger-doc/releases/tag/v0.2.2-0

**Comment by jellydn** [comment]
Well, I could refer to the `yaml` file on my example. You should check it out by this commit https://github.com/jellydn/next-swagger-doc/commit/6e295bfec5fe693a7e2c407ce63018159c63efc8 @MGough
