### ISSUE TITLE
Error when adding a Request Body to a Post Request

### ISSUE THREAD

**Issue by bigvisionmalachibazar** [jellydn/next-swagger-doc#203]
Hello,

I'm having trouble with adding a request body to a post request. When I add the request body and load the Swagger docs page on my localhost, I get a console error: 

```error
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code.
```
I haven't modified the default `docs.ts` file in /api or the `api-doc.tsx` shown in the repo example.

Here's my JSdoc:

```javascript
/**
 * @swagger
 * /api/admin/users/new-user:
 *
 *   post:
 *     tags:
 *      - Admin
 *     description: Create a new user with a post request
 *     requestBody:
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               name:
 *                 type: string
 *     responses:
 *       201:
 *         description: User created
 *       401:
 *         description: Unauthorized
 *       500:
 *         description: Internal Server Error
 */
```

**Comment by jellydn** [comment]
This warning is from a React component that has `UNSAFE_componentWillReceiveProps`. It's not related to `next-swagger-doc`. I guess that's coming from react-swagger-ui 🤔 Could you please check the console warning stack? Thanks.
