### ISSUE TITLE
Fs module error while using package. 

### ISSUE THREAD

**Issue by devanshSingh5656** [jellydn/next-swagger-doc#26]
Module not found: Can't resolve 'fs'.

![Capture1](https://user-images.githubusercontent.com/81424670/123503124-7dc8f280-d66e-11eb-9fe9-3e1261c3a182.PNG)

i try to resolve it so i use this in NEXT config file the error resolve and it work perfectly in local 

BUT WHEN DEPLOY TO SERVER IT WON'T WORK.
![Capture](https://user-images.githubusercontent.com/81424670/123503169-e021f300-d66e-11eb-924f-f3b601f42baf.PNG)

webpack: (config, { isServer }) => {
    // Fixes npm packages that depend on `fs` module
    if (!isServer) {
      config.node = {
        fs: "empty",
      };
    }

PLEASE PROVIDE HELP ASAP.

**Comment by jellydn** [comment]
Hi @devanshSingh5656. Thank you for your report. Could you tell me the usage? Which one are you using? https://github.com/jellydn/next-swagger-doc#usage-1-create-an-single-api-document or https://github.com/jellydn/next-swagger-doc#usage-2-use-nextjs-api-route-for-create-swagger-json-spec

It would be helpful for me investigating if you share the package.json and next.config.js. Thanks.

**Comment by jellydn** [comment]
At first glance, I guess the `fs` is a native module on NodeJs and you got the error with `fs` module which means you're calling `serverside function` from the browser. 🤔

**Comment by jellydn** [comment]
Please check the example app https://github.com/jellydn/next-swagger-doc/blob/main/example/README.md if you want to see how it works. Thanks.

**Comment by devanshSingh5656** [comment]
i am using createSwaggerSpec for multiple api's but it throws the error 

but when i use with changes in next config C:\Users\devan\Desktop\NEXTJS\api\next.config.js

it works but when i deployed it on server api's are not visible
![Capture](https://user-images.githubusercontent.com/81424670/123503864-5163a500-d673-11eb-88e0-8bc55b469d3f.PNG)
C:\Users\devan\Desktop\NEXTJS\api\package.json

**Comment by jellydn** [comment]
re.
```
it works but when i deployed it on server api's are not visible
```
So it's working on local but it's showing empty on production deployment, right? Interesting 🤔 . How do you set up the deployment? It could give me some insights to think about this. Thanks.

**Comment by jellydn** [comment]
Hi @devanshSingh5656 Please check out the latest version https://github.com/jellydn/next-swagger-doc/releases/tag/v0.1.7 Let me know if that works for you. Thanks.

**Comment by devanshSingh5656** [comment]
used vercel deployment

**Comment by jellydn** [comment]
It shouldn't be an issue anymore. My example app is also deployed to vercel.

**Comment by devanshSingh5656** [comment]
can you make the package available on npm?

**Comment by jellydn** [comment]
It's published on npm already.
