### ISSUE TITLE
How to define a api's path ?

### ISSUE THREAD

**Issue by devanshSingh5656** [jellydn/next-swagger-doc#27]
how to customly give api path when we have folder sturcture in it.
![Captureqw](https://user-images.githubusercontent.com/81424670/123512085-1f6a3700-d6a3-11eb-8432-85cc4bbb059a.PNG)

**Comment by jellydn** [comment]
Hi @devanshSingh5656 Will update the readme about this config.

```
/**
 * Create swagger JSON
 * @param options.openApiVersion Open API version {3.0.0}
 * @param options.apiFolder NextJS API folder {pages/api}
 * @param options.title Title
 * @param options.version Version
 * @returns Swagger JSON Spec
 *
 * @example
 * createSwaggerSpec({
 *  openApiVersion: '3.0.0',
 *  apiFolder:  'pages/api',
 *  title: 'Demo Api',
 *  version: '1.0',
 * })
 */
```

**Comment by jellydn** [comment]
FYI, you should see that on readme now. https://github.com/jellydn/next-swagger-doc/releases/tag/v0.1.8

https://github.com/jellydn/next-swagger-doc#usage-2-use-nextjs-api-route-for-create-swagger-json-spec

**Comment by devanshsinghvaluecoders** [comment]
Hey Good work, but please update latest version on npm also

**Comment by jellydn** [comment]
Yeah, I have already published on Npm :)
