### ISSUE TITLE
Issue with parameters and swcMinify

### ISSUE THREAD

**Issue by billythedummy** [jellydn/next-swagger-doc#515]
reported here: https://github.com/vercel/next.js/issues/41992

**Comment by kdy1** [comment]
It's an issue of swc minifier and will be fixed by https://github.com/swc-project/swc/pull/6282, which is waiting for a code review

**Comment by jellydn** [comment]
Thanks both. In the meantime, I would recommend to use as CLI, refer https://github.com/jellydn/next-swagger-doc#usage-3-generate-swagger-file-from-cli
