### ISSUE TITLE
Authorize using Bearer or OAuth2

### ISSUE THREAD

**Issue by uchetfield** [jellydn/next-swagger-doc#653]
### Describe the bug

Is there way to configure swagger for different types of security?

I found a discussion [here](https://stackoverflow.com/questions/50736784/how-to-authorise-swagger-jsdoc-with-jwt-token) that we could configure security in the format below.

```
const swaggerOptions = {
  swaggerDefinition: {
    openapi: '3.0.1', // YOU NEED THIS
    info: {
      title: 'Your API title',
      version: '1.0.0',
      description: 'Your API description'
    },
    basePath: '/',
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        }
      }
    },
    security: [{
      bearerAuth: []
    }]
  },
  apis: ['/some/path.js|yml'],
};
```

I'm using NextJS 12 and configuring my docs using the code below.

```
import { withSwagger } from "next-swagger-doc";

const swaggerHandler = withSwagger({
  definition: {
    openapi: "3.0.0",
    info: {
      title: "OTLS-API",
      version: "1.39.0",
    },
  },
  apiFolder: "pages/api",
});
export default swaggerHandler();
```
I wasn't able to configure a security parameter in the definition.  Is there an example of how I can do this?   

### Reproduction

Reproduction

### System Info

```Shell
NextJS 12
`next-swagger-doc` 0.3.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by credas-dev** [comment]
Created discussion #655
