### ISSUE TITLE
README Documentation has a missing dependency

### ISSUE THREAD

**Issue by KartikDotDev** [jellydn/next-swagger-doc#923]
The command ```yarn add next-swagger-doc``` is missing the swagger-ui-react library addition and an important note for TS users to install @types/swagger-ui-react as a dev dependency, I'll create a merge request for it soon.

**Comment by jellydn** [comment]
> swagger-ui-react

It's an optional package that you can use any swagger UI library.  E.g: https://github.com/stoplightio/elements

**Comment by KartikDotDev** [comment]
The step 2 of Usage 1 uses swagger-ui-react and provides no NB/Disclaimer that any newbie can use any library whatsoever. Thus swagger-ui-react needed to be mentioned for onboarding newbies.
![image](https://github.com/jellydn/next-swagger-doc/assets/90651659/d4c6c001-8d23-4914-b579-d9f712dae718)
See above screenshot of Readme for proof.
