### ISSUE TITLE
Error after upgrading to next@12.0.0

### ISSUE THREAD

**Issue by trentprynn** [jellydn/next-swagger-doc#97]
Hey!

Really love this project, you can [see it in production here](https://habitapper.com/documentation) for the habit tracking web app I've been working on in my off time!

You can see my code for the documentation page generation [here](https://github.com/trentprynn/habitapper.com/blob/master/pages/documentation.tsx)

Currently I'm starting to look at upgrading my application to next@12.0.0 and I noticed that when I go to documentation page after upgrading versions I get the following error

```js
./node_modules/swagger-ui-react/swagger-ui.js:2:305499
Module not found: Can't resolve 'isarray'

Import trace for requested module:
./node_modules/swagger-ui-react/index.js
./pages/documentation.tsx

https://nextjs.org/docs/messages/module-not-found
```

This reads like a problem in swagger-ui-react so not sure if there's anything to do here but I figured I'd open up this issue to start getting the ball rolling on next@12 support!

**Comment by trentprynn** [comment]
@jellydn I believe this is actually is an issue, please take a look at the following stackblitz reproductions (they must be opened using chrome) and observe that when using next@12 + next-swagger-doc it has the 'isarray' import error I originally mentioned

next@11.1.2 + next-swagger-doc@1.10.0 => [WORKING](https://stackblitz.com/edit/nextjs-rlxnx5?devtoolsheight=33&file=package.json)

next@12.0.1 + next-swagger-doc@1.10.0  => [BROKEN](https://stackblitz.com/edit/nextjs-xnhchk?devtoolsheight=33&file=package.json)

**Comment by trentprynn** [comment]
also it seems like all your vercel builds are failing for your demo site deployments to vercel after your upgrade to next@12 and I would bet it's because of the same problem

<img width="1343" alt="Screen Shot 2021-10-30 at 8 42 05 AM" src="https://user-images.githubusercontent.com/22459581/139539916-c49baddf-9482-428e-a3fb-93a1e6185e01.png">

**Comment by jellydn** [comment]
Thanks @trentprynn 

Quite weird as it's working when I tested with example app.

```
mkdir test
npx degit jellydn/next-swagger-doc/example
yarn && yarn build && yarn start
```
You're correct. I saw the same error on Vercel build. Let me take a look.

**Comment by jellydn** [comment]
FYI
```sh


[4/4] Building fresh packages...
--
10:58:22.314 | Done in 34.95s.
10:58:22.339 | Detected Next.js version: 12.0.1
10:58:22.341 | Running "yarn run build"
10:58:22.684 | yarn run v1.22.17
10:58:22.744 | $ next build
10:58:23.588 | info - Checking validity of types...
10:58:28.020 | info - Creating an optimized production build...
10:58:52.447 | Failed to compile.
10:58:52.448 | ./node_modules/swagger-ui-react/swagger-ui.js
10:58:52.449 | Module not found: Can't resolve 'isarray' in '/vercel/path0/example/node_modules/swagger-ui-react'
10:58:52.449 | Import trace for requested module:
10:58:52.449 | ./node_modules/swagger-ui-react/index.j


```

**Comment by trentprynn** [comment]
@jellydn I'm pretty sure it's not actually a problem with your library, I think it's an issue with either next@12 or swagger-ui-react

I removed the dependency on next-swagger-doc and can recreate the same problem (repro's must be viewed using chrome)

next@11.1.2 + swagger-ui-react@3.52.5 => [WORKING](https://stackblitz.com/edit/nextjs-gj6qtj?devtoolsheight=33&file=package.json)

next@12.0.1 + swagger-ui-react@3.52.5 => [BROKEN](https://stackblitz.com/edit/nextjs-ncwgpm?devtoolsheight=33&file=package.json)

I'll go ahead and open up an issue in the with next in a minute

**Comment by jellydn** [comment]
Great. Thanks.

**Comment by trentprynn** [comment]
@jellydn went ahead and opened this issue https://github.com/vercel/next.js/issues/30669

you might want to re-open this issue so users are not confused by this error if they try to use this library (which ends up using swagger-ui-react) and next@>=12

**Comment by trentprynn** [comment]
Also, as a temporary fix, if you manually add [https://www.npmjs.com/package/isarray](isarray) to your project's dependencies the error does not occur

**Comment by jellydn** [comment]
Agreed. Tganks.

**Comment by trentprynn** [comment]
@jellydn I just tested and this is still an issue, do you think you could make `isarray` a `next-swagger-doc` dependency so end users don't have to add to add the dependency to their project?

**Comment by jellydn** [comment]
Ok, no problem. Thanks. Will do this today.

**Comment by jellydn** [comment]
Close with https://github.com/jellydn/next-swagger-doc/releases/tag/v0.1.11
